### ISSUE TITLE
Will the project be open source?

### ISSUE THREAD

**Issue by a2821952** [MarkFzp/Deep-Whole-Body-Control#2]
Hello, I read this paper many times, and it has a lot of value. So I have been waiting for formal open source, but there is no progress for several months. May I ask when this project will be open-source formal?

**Comment by MarkFzp** [comment]
Thanks for your interests in this project! I'll try my best to open source it within this Feb. The process was delayed by the my other projects and commitments. Sorry about that!

**Comment by a2821952** [comment]
Thank you for your answer. I look forward to it.

**Comment by boxiXia** [comment]
Looking forward to seeing it open-sourced!

**Comment by Murkey8895** [comment]
Looking forward to this awesome work !

**Comment by MarkFzp** [comment]
The update timeline will be the week after June 8th as I'm currently swamped several ongoing CoRL projects. Thanks for your patience! I'm updating the urdf for the robot first, so people can play around with it before the final release.

**Comment by Yinghui-Lee** [comment]
Looking forward!

**Comment by DZQ-Niente** [comment]
Looking forward to seeing such excellent work open-sourced!

**Comment by YESAndy** [comment]
Looking forward!
